import React from 'react';
import {createRoot} from 'react-dom/client';
import {Github,ExternalLink,Mail,Send,ArrowDown,Code2,Menu,X,Globe2,ArrowUpRight} from 'lucide-react';
import './style.css';

type Lang='ru'|'en';
const projects=[
{name:'Blanchard',ru:'Адаптивный арт-проект с интерактивными элементами и подключением API Wikipedia.',en:'Responsive art project with interactive UI and Wikipedia API integration.',stack:['HTML','CSS','JavaScript','API'],repo:'https://github.com/PavelSed33/Blanchard',demo:'https://pavelsed33.github.io/Blanchard/'},
{name:'Evklid',ru:'Адаптивный сайт строительной компании с аккуратной версткой и интерактивным интерфейсом.',en:'Responsive construction company website with precise layout and interactive UI.',stack:['HTML','CSS','JavaScript'],repo:'https://github.com/PavelSed33/Evklid',demo:'https://pavelsed33.github.io/Evklid/'},
{name:'EleganceShop',ru:'Интерфейс интернет-магазина с фокусом на современную визуальную подачу и адаптивность.',en:'E-commerce interface focused on modern visual presentation and responsive design.',stack:['HTML','CSS','JavaScript'],repo:'https://github.com/PavelSed33/EleganceShop',demo:'https://pavelsed33.github.io/EleganceShop/'},
{name:'Lagoona',ru:'Адаптивный лендинг гостиничного сервиса с семантичной структурой и детальной версткой.',en:'Responsive hotel service landing page with semantic structure and detailed layout.',stack:['HTML','CSS'],repo:'https://github.com/PavelSed33/Lagoona',demo:'https://pavelsed33.github.io/Lagoona/'}];
const copy={ru:{nav:['Обо мне','Навыки','Проекты','Контакты'],eyebrow:'FRONTEND РАЗРАБОТЧИК',lead:'Создаю современные, быстрые и адаптивные веб-интерфейсы. В разработке с 2021 года.',view:'Смотреть проекты',aboutLabel:'01 / ОБО МНЕ',aboutTitle:<>Превращаю идеи<br/>в <em>интерфейсы.</em></>,about1:'Я frontend-разработчик, занимаюсь веб-разработкой с 2021 года. Работаю на фрилансе и создаю пользовательские интерфейсы — от точной реализации дизайна до готового адаптивного продукта.',about2:'Уделяю внимание чистоте кода, производительности, доступности и корректной работе интерфейса на разных устройствах.',since:'Начало разработки',work:'Формат работы',skillsLabel:'02 / НАВЫКИ',skillsTitle:<>Технологии, с которыми<br/>я <em>работаю.</em></>,projectsLabel:'03 / ПРОЕКТЫ',projectsTitle:<>Избранные <em>работы.</em></>,all:'Все репозитории',demo:'Открыть сайт',code:'Код',contactLabel:'04 / КОНТАКТЫ',contactTitle:<>Есть проект?<br/><em>Давайте обсудим.</em></>,contactText:'Открыт к фриланс-проектам и интересным предложениям по frontend-разработке.',name:'Ваше имя',email:'Email',message:'Расскажите о проекте',send:'Отправить сообщение',direct:'Или напишите напрямую',years:'5+ лет',yearsSub:'в веб-разработке'},en:{nav:['About','Skills','Projects','Contact'],eyebrow:'FRONTEND DEVELOPER',lead:'I build modern, fast and responsive web interfaces. Developing for the web since 2021.',view:'View projects',aboutLabel:'01 / ABOUT',aboutTitle:<>Turning ideas<br/>into <em>interfaces.</em></>,about1:'I am a frontend developer working in web development since 2021. As a freelancer, I build user interfaces from precise design implementation to complete responsive products.',about2:'I care about clean code, performance, accessibility and reliable interfaces across different devices.',since:'Started development',work:'Work format',skillsLabel:'02 / SKILLS',skillsTitle:<>Technologies I<br/><em>work with.</em></>,projectsLabel:'03 / PROJECTS',projectsTitle:<>Selected <em>work.</em></>,all:'All repositories',demo:'Live demo',code:'Code',contactLabel:'04 / CONTACT',contactTitle:<>Have a project?<br/><em>Let’s talk.</em></>,contactText:'Available for freelance projects and interesting frontend development opportunities.',name:'Your name',email:'Email',message:'Tell me about your project',send:'Send message',direct:'Or contact me directly',years:'5+ years',yearsSub:'in web development'}};
function App(){
 const[open,setOpen]=React.useState(false);const[lang,setLang]=React.useState<Lang>('ru');const t=copy[lang];
 React.useEffect(()=>{const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>io.observe(el));return()=>io.disconnect()},[lang]);
 const submit=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const fd=new FormData(e.currentTarget);const subject=encodeURIComponent(`Portfolio: ${fd.get('name')}`);const body=encodeURIComponent(`${fd.get('message')}\n\n${lang==='ru'?'Ответить':'Reply to'}: ${fd.get('email')}`);window.location.href=`mailto:Peresvetovec@gmail.com?subject=${subject}&body=${body}`};
 const navIds=['about','skills','projects','contact'];
 return <><header><a className="logo" href="#top">PS<span>.</span></a><nav className={open?'open':''}>{t.nav.map((x,i)=><a key={x} onClick={()=>setOpen(false)} href={'#'+navIds[i]}>{x}</a>)}</nav><div className="headActions"><button className="lang" onClick={()=>setLang(lang==='ru'?'en':'ru')}><Globe2 size={15}/>{lang==='ru'?'EN':'RU'}</button><a className="gh top" href="https://github.com/PavelSed33" target="_blank" rel="noreferrer"><Github size={18}/> GitHub</a></div><button className="menu" aria-label="Menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></header>
 <main id="top"><section className="hero"><div className="heroText"><div className="eyebrow"><span/> {t.eyebrow}</div><h1>Седых<br/><em>Павел</em></h1><p>{t.lead}</p><div className="actions"><a className="primary" href="#projects">{t.view} <ArrowDown size={18}/></a><a className="secondary" href="https://github.com/PavelSed33" target="_blank" rel="noreferrer"><Github size={18}/> GitHub</a></div></div><div className="portrait"><div className="orbit orbit1"/><div className="orbit orbit2"/><div className="glow"/><img src="https://github.com/PavelSed33.png?size=460" alt="Седых Павел"/><div className="badge"><Code2/><div><b>{t.years}</b><small>{t.yearsSub}</small></div></div><span className="floatTag">&lt;frontend /&gt;</span></div></section>
 <section id="about" className="about reveal"><div><span className="num">{t.aboutLabel}</span><h2>{t.aboutTitle}</h2></div><div className="aboutText"><p>{t.about1}</p><p>{t.about2}</p><div className="stats"><div><b>2021</b><small>{t.since}</small></div><div><b>Freelance</b><small>{t.work}</small></div></div></div></section>
 <section id="skills" className="reveal"><span className="num">{t.skillsLabel}</span><h2>{t.skillsTitle}</h2><div className="skills">{['HTML5','CSS3 / SCSS','JavaScript','Responsive UI','REST API','Git / GitHub'].map((s,i)=><div className="skill" key={s}><span>0{i+1}</span><b>{s}</b></div>)}</div></section>
 <section id="projects" className="reveal"><span className="num">{t.projectsLabel}</span><div className="sectionHead"><h2>{t.projectsTitle}</h2><a href="https://github.com/PavelSed33?tab=repositories" target="_blank" rel="noreferrer">{t.all} <ExternalLink size={16}/></a></div><div className="projectGrid">{projects.map((p,i)=><article className="projectCard" key={p.name}><a className="preview" href={p.demo} target="_blank" rel="noreferrer"><iframe title={`${p.name} preview`} src={p.demo} loading="lazy" tabIndex={-1}/><div className="previewFallback"><Code2/><span>{p.name}</span></div><span className="previewNo">0{i+1}</span><span className="previewOpen"><ArrowUpRight/></span></a><div className="projectBody"><h3>{p.name}</h3><p>{p[lang]}</p><div className="tags">{p.stack.map(x=><span key={x}>{x}</span>)}</div><div className="projectLinks"><a href={p.demo} target="_blank" rel="noreferrer"><ExternalLink size={15}/>{t.demo}</a><a href={p.repo} target="_blank" rel="noreferrer"><Github size={15}/>{t.code}</a></div></div></article>)}</div></section>
 <section id="contact" className="contact reveal"><div className="contactIntro"><span className="num">{t.contactLabel}</span><h2>{t.contactTitle}</h2><p>{t.contactText}</p><small>{t.direct}</small><div className="directLinks"><a href="https://t.me/Peresvetovec" target="_blank" rel="noreferrer"><Send size={18}/>@Peresvetovec</a><a href="mailto:Peresvetovec@gmail.com"><Mail size={18}/>Peresvetovec@gmail.com</a></div></div><form onSubmit={submit}><label><span>{t.name}</span><input name="name" required autoComplete="name"/></label><label><span>{t.email}</span><input name="email" type="email" required autoComplete="email"/></label><label><span>{t.message}</span><textarea name="message" rows={5} required/></label><button className="primary" type="submit">{t.send}<Send size={17}/></button></form></section></main>
 <footer><span>© 2026 Седых Павел</span><div className="footerLinks"><a href="https://github.com/PavelSed33" target="_blank" rel="noreferrer" aria-label="GitHub"><Github size={19}/><span>GitHub</span></a><a href="https://t.me/Peresvetovec" target="_blank" rel="noreferrer" aria-label="Telegram"><Send size={19}/><span>Telegram</span></a><a href="mailto:Peresvetovec@gmail.com" aria-label="Email"><Mail size={19}/><span>Gmail</span></a></div><span>Frontend Developer</span></footer></>}
createRoot(document.getElementById('root')!).render(<App/>);
